### ISSUE TITLE
/commands/blackjack - recognizes ANYTHING put after by the command 

### ISSUE THREAD

**Issue by xplrkai** [mxttx/okbot-issue-tracker#2]
## Summary
The bot recognizes any text that is said after 'ok bj <amount>' from the person who executed the command. Because of this, if you attempt to reply with h, s or e, it wouldn't work.

## Expected Behavior
It's supposed to ignore anything except the expected h, s or e replies.

## Current Behavior
The bot recognizes **any** text that is said after 'ok bj <amount>' from the person who executed the command. Because of this, if you attempt to reply with h, s or e, it wouldn't work.

## Steps to Reproduce

1. enter the command 'ok bj <amount>'
2. type anything after the command is executed
3. attempt to answer with h, s or e

## Background (Discord ID and screenshots if possible)
![Discord_G7mSNCVICp](https://user-images.githubusercontent.com/37079112/92406308-9c85e900-f12f-11ea-8046-d98b82d6d2b8.png)
xplrkai#0100

**Comment by mxttx** [comment]
Thank you for the bug report - but this cannot be fixed due to the way the command is coded.

You may know that the command is currently also being reworked, though again I cannot add a fix for this. 
I have however added a reply that the bot will send if you do mess up whilst betting using blackjack.

You will also not receive any money back for messing up as this can be abused. Ideally, if you start a blackjack game you should be prepared to see it through to the end.
